Landfast Sea Ice: Explore, Characterize, and Document
ua-snap/ardac-curation pull request #1
Opened 2022-08-04 23:08 UTC by charparr

This PR represents the exploration and documentation of phases of the data ingest pipeline for "the Landfast Sea Ice Data."

To analyze this PR, revisit the [ARDAC data ingest pipeline.](https://docs.google.com/document/d/1hw-QzEB-9x79tT6YlNaBFoB9V4SU40f3pKPO6QL52rU/edit#heading=h.91nosl9tpnep) and determine whether or not we've done enough due diligence to move ahead to the distillation and pre-processing phase, for which a recommendation is made in the Jupyter Notebooks and in the `landfast_eda` Markdown file.

Note that we are awaiting feedback from our subject matter experts (Mahoney, Eicken) that could inform the next phase of the ingest.

Some suggestions

- [x] Did we learn the file naming conventions?
- [x] Did we investigate all the flavors of data that are present?
- [x] Do have a handle on what the spatial references and nodata values are, and what steps we might need to take to address any shortfalls?
- [x] Did we visualize the data, and does it pass the eyeball test?

Both notebooks (NSIDC and Mahoney) are set up to be ran on Atlas, but don't need to be ran for this PR because they aren't actually doing any processing or creating any new datasets.

However, you can run them on an Atlas Compute Node by activating an `anaconda-project` environment and then launching a notebook with this command or similar:

`anaconda-project run jupyter notebook --no-browser --port 8887`

See the [pipeline template](https://github.com/ua-snap/pipeline-template) for anaconda-project usage.

2022-08-12 22:17 UTC, charparr commented
After 8 days feedback from domain experts (Mahoney, Eicken) is pending and we're already moving forward with some pre-processing work so this moving out of draft and into review. We can revise or update this work later on.

2022-08-16 01:13 UTC, cstephen requested changes
Everything looks great overall and this is super informative for someone like me who hasn't dealt with this data yet. Awesome work! The following two files could benefit from a spell & grammar check, however:

- `landfast_NSIDC.ipynb`
- `landfast_eda.md`

2022-08-16 03:20 UTC, kyleredilla requested changes
This is data exploration at it's finest! Really great work in figuring what we have been given and how it relates to what is in the wild. I've ran through both notebooks and things look great. There were a couple of minor suggestions I was going to make in the notebooks, but re-executing the notebook cells was causing all sorts of meaningless changes in the outputs of the `tree` cells and having to wade through those just to see the minor edits I was going to make didn't seem worth the trouble (and the diffs were too large to view on GH). Basically I agree with Craig's comment to just do a scan for typo stuff and it's g2g after that. I did request some typo changes on the markdown file.

2022-08-16 03:20 UTC, kyleredilla commented on anaconda-project.yml
>  #
we can add this code at the end of the document to prevent messages like this: 

```
Potential issues with this project:
  * anaconda-project.yml: No commands run notebooks seaice/landfast_NSIDC.ipynb, seaice/landfast_mahoney.ipynb
```

from popping up with `anaconda-project run ...`

```
# This is a temporary fix to remove warnings 
# about notebooks without commands
skip_imports:
  notebooks: true
```

I just can't suggest it as a change down there because that part of the doc was not edited in this branch. Well, technically you could probably add it wherever you wanted to in the file.

2022-08-16 03:20 UTC, kyleredilla commented on seaice/landfast_eda.md
> +The purpose of this document is a high-level distillation of the progress made toward identifying, collecting, and curating "the landfast sea ice data" for integration into the Arctic Data Collaborat
```suggestion
The purpose of this document is a high-level distillation of the progress made toward identifying, collecting, and curating "the landfast sea ice data" for integration into the Arctic Data Collaborative (ARDAC). This document describes the current understanding of the data and proposes the next step forward in making these data more broadly accessible and useful with the ultimate aim of a wider variety of end-users.
```

2022-08-16 03:20 UTC, kyleredilla commented on seaice/landfast_eda.md
> +Landfast ice is sea ice that is mostly stationary and attached to land. Specifically, landfast ice is defined here as being continguous to the coast and lacking detectable motion for approximately 20
Again, really awesome sleuthing, here.

2022-08-16 03:20 UTC, kyleredilla commented on seaice/landfast_eda.md
> +>In the Arctic, landfast sea ice is a key element of the coastal system, integral to a wide range of geological and biological processes as well as human activities. The presence of landfast ice can
```suggestion
>In the Arctic, landfast sea ice is a key element of the coastal system, integral to a wide range of geological and biological processes as well as human activities. The presence of landfast ice can mitigate the effect of winter storms on the coast but also impede navigation in the spring. As well as being of great importance to native subsistence activities [Nelson, 1969; George et al., 2004], the presence or absence of landfast ice in northern Alaska and its stability are of considerable economic importance for offshore development.
```

Blown away by all of this info you've compiled and how you've presented it!

2022-08-16 03:20 UTC, kyleredilla commented on seaice/landfast_eda.md
> +The landfast ice data are derived from RADARSAT-1 data aquired using the the moderate-resolution ScanSAR operation mode of the synthetic aperture radar (SAR) sensor. The RADARSAT-1 mission (no longer
```suggestion
The landfast ice data are derived from RADARSAT-1 data aquired using the the moderate-resolution ScanSAR operation mode of the synthetic aperture radar (SAR) sensor. The RADARSAT-1 mission (no longer active) used a C-Band (5.3 GHz), 5.6 cm wavelength, HH polarized microwave frequency to image the earth. RADARSAT-1 could "detect" landfast ice because it has a distinct backscatter signature compared to surrounding pack ice, land, or open water. Indiviudal ScarSAR passes were mosaicked together to generate a mosaic every two or three days resulting in 8 to 35 mosaics per annual ice cycle. Data processing details are provided by [Eicken et al. (2006)](https://nsidc.org/sites/nsidc.org/files/files/data/noaa/g02173/eicken_leads_landfast_2006.pdf).
```

2022-08-16 03:20 UTC, kyleredilla commented on seaice/landfast_eda.md
> +I recommend we prioritize create a unified landfast ice extent datacube for ingest into ARDAC via an integration with our array geodatabase (Rasdaman) and SNAP Data API. A discrete daily time index w
```suggestion
I recommend we prioritize creating a unified landfast ice extent datacube for ingest into ARDAC via an integration with our array geodatabase (Rasdaman) and SNAP Data API. A discrete daily time index will serve as the "third dimension" of this datacube and be a mechanism by which users can request, slice, and access data. This will require mapping the DOY ranges provided by the GeoTIFF file names to this index to control for which data (Chukchi, Beaufort, both) are available for which times. This effort will also require determining the extent to which the NSDIC (Figure 1) and the InteRFACE-Beaufort (Figure 3) datasets are identical. As there are different numbers of GeoTIFFs available from each, it is possible that one is a subset of the other. Wherever we are fusing the InteRFACE data with the NSIDC data we'll need to prescribe a common set of categorical integer encodings (e.g., 128 is always the landmask). The ultimate outcome would be for a user to be able to query the dataset by a date or set of dates and retrieve an internally consistent set of whatever landfast sea ice data exists for that period. In my opinion this work would represent a substantial upgrade to the accessibility and usability of these datasets for technical users.
```

Excellent.

2022-08-17 20:31 UTC, charparr commented
Thanks for the thorough review on this one! The notebooks and summary documents are proofed to the point where if external eyeballs take a look it won't be embarrassing. I'll follow this up with another PR soon for the next phase of the ARDAC ingest process: Distillation + Preprocessing. I may ask you both for a review on that as well since you're "read in" to these data already.

2022-08-19 22:05 UTC, cstephen approved these changes

2022-08-19 22:36 UTC, merged